- hosts: all
  name: Clear cached facts
  tasks:
    - meta: clear_facts

- hosts: "{{ deploy_source_host }}"
  name: Gather facts from undercloud
  gather_facts: yes
  any_errors_fatal: true
  ignore_unreachable: "{{ scale_ignore_unreachable | default(false) }}"
  become: false
  tags:
    - facts

- hosts: "{{ deploy_target_host }}"
  name: Gather facts from overcloud
  gather_facts: yes
  # False because https://github.com/ansible/ansible/issues/70663
  any_errors_fatal: false
  ignore_unreachable: "{{ scale_ignore_unreachable | default(false) }}"
  tags:
    - facts

- hosts: all
  name: Load global variables
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: false
  ignore_unreachable: "{{ scale_ignore_unreachable | default(false) }}"
  tasks:
    - include_vars: global_vars.yaml
      no_log: true
  tags:
    - always

- hosts: "{{ deploy_target_host }}"
  name: Render all_nodes data as group_vars for overcloud
  gather_facts: "{{ gather_facts | default(false) }}"
  # we don't skip errors or ignore unreachable on this one because it's
  # delegated to localhost. localhost should never be unreachable (tm)
  any_errors_fatal: True
  tasks:
    - name: Render all_nodes data as group_vars for overcloud
      delegate_to: localhost
      become: false
      run_once: true
      when: not ansible_check_mode|bool
      tripleo_all_nodes_data:
  tags:
    - facts
    - always

- hosts: "{{ deploy_target_host }}"
  name: Set all_nodes data as group_vars for overcloud
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: false
  ignore_unreachable: "{{ scale_ignore_unreachable | default(false) }}"
  tasks:
    - name: Set all_nodes data as group_vars for overcloud
      include_vars: "{{ playbook_dir }}/group_vars/overcloud.json"
      no_log: true
      when: not ansible_check_mode|bool
  tags:
    - facts
    - always
